#lang racket

; **Exercise 1.9**: Each of the following two procedures defines a
; method for adding two positive integers in terms of the procedures
; `inc`, which increments its argument by 1, and `dec`, which decrements
; its argument by 1.

; ```
; (define (inc x) (+ x 1))
; (define (dec x) (- x 1))

; (define (plus a b)
;   (if (= a 0) 
;       b 
;       (inc (plus (dec a) b))))

; (define (plus a b)
;   (if (= a 0) 
;       b 
;       (plus (dec a) (inc b))))
; ```

; Using the substitution model, illustrate the process generated by each
; procedure in evaluating `(plus 4 5)`.  Are these processes iterative or
; recursive?

(define (inc x) (+ x 1))
(define (dec x) (- x 1))

(define (plus a b)
  (if (= a 0) 
      b 
      (inc (plus (dec a) b))))

(plus 4 5)
;(if (= 4 0) 5 (inc (plus (dec 4) 5))))
;(inc (plus (dec 4) 5))))
;continuar

(define (plus2 a b)
  (if (= a 0) 
      b 
      (plus (dec a) (inc b))))