#lang racket

;Hecho por 
; EZQUERRA CEBALLOS, CARLOS
; FERNÁNDEZ RIVERA, CRISTIAN MANUEL
; GOMEZ GARCIA, GABRIEL
; MUÑOZ FERNANDEZ, PAULA

#|
Exercise 1.9: Each of the following two procedures defines a method for adding two positive integers 
in terms of the procedures inc, which increments its argument by 1, and dec, which decrements its argument by 1.

(define (inc x) (+ x 1))
(define (dec x) (- x 1))

Define the first version of the plus function
(define (plus a b)
  (if (= a 0) 
      b 
      (inc (plus (dec a) b))))

; Define the second version of the plus function
(define (plus a b)
  (if (= a 0) 
      b 
      (plus (dec a) (inc b))))

Using the substitution model, illustrate the process generated by each procedure in evaluating (plus 4 5). 
Are these processes iterative or recursive?
|#

;RESPUESTA

#|
Proceso para la primera versión de `plus`:
(plus 4 5) → (inc (plus 3 5))
(plus 3 5) → (inc (plus 2 5))
(plus 2 5) → (inc (plus 1 5))
(plus 1 5) → (inc (plus 0 5))
(plus 0 5) → 5
Por lo tanto: (plus 1 5) → (inc 5) → 6
(plus 2 5) → (inc 6) → 7
(plus 3 5) → (inc 7) → 8
(plus 4 5) → (inc 8) → 9
Este proceso es recursivo ya que involucra múltiples niveles de llamadas a la función.

Proceso para la segunda versión de `plus`:
(plus 4 5) → (plus 3 6)
(plus 3 6) → (plus 2 7)
(plus 2 7) → (plus 1 8)
(plus 1 8) → (plus 0 9)
(plus 0 9) → 9
Este proceso también es recursivo, ya que involucra múltiples niveles de llamadas a la función con un argumento modificado.
|#
