#lang racket
;Exercise 1.9: Each of the following two procedures defines a method for adding two positive integers in terms of the procedures inc,
;which increments its argument by 1, and dec, which decrements its argument by 1.

(define (inc x) (+ x 1))
(define (dec x) (- x 1))

(define (plus a b)
  (if (= a 0) 
      b 
      (inc (plus (dec a) b))))

(define (plus a b)
  (if (= a 0) 
      b 
      (plus (dec a) (inc b))))

;Using the substitution model, illustrate the process generated by each procedure in evaluating (plus 4 5). Are these processes iterative or recursive?

(define (plus a b)
  (if (= a 0) 
      b 
      (inc (plus (dec a) b))))

;MEDIANTE EL PRIMER PROCEDURE
;(plus 4 5)
;(if (= 4 0) 5 (inc (plus (dec 4) 5)))
;(inc (plus (dec 4) 5))
;(+ (plus (- 4 1) 5) 1)
;(+ (plus 3 5) 1)
;(+ (if (= 3 0) 5 (inc (plus (dec 3) 5))) 1)
;(+ (inc (plus (dec 3) 5)) 1)
;(+ (+ (plus (- 3 1) 5) 1) 1)
;(+ (+ (plus 2 5) 1) 1)
;(+ (+ (if (= 2 0) 5 (inc (plus (dec 2) 5))) 1) 1)
;(+ (+ (inc (plus (dec 2) 5)) 1) 1)
;(+ (+ (+ (plus (- 2 1) 5) 1) 1) 1)
;(+ (+ (+ (plus 1 5) 1) 1) 1)
;(+ (+ (+ (if (= 1 0) 5 (inc (plus (dec 1) 5))) 1) 1) 1)
;(+ (+ (+ (inc (plus (dec 1) 5)) 1) 1) 1)
;(+ (+ (+ (+ (plus (dec 1) 5) 1) 1) 1) 1)
;(+ (+ (+ (+ (if (= 0 0) 5 (inc (plus (dec 0) 5)))) 1) 1) 1) 1)
;(+ (+ (+ (+ 5 1) 1) 1) 1)
;(+ (+ (+ 6 1) 1) 1)
;(+ (+ 7 1) 1)
;(+ 8 1)
;9

;Es recursivo porque dejas operaciones pendientes que luego tienes que hacer

(define (plus a b)
  (if (= a 0) 
      b 
      (plus (dec a) (inc b))))

;MEDIANTE EL SEGUNDO PROCEDURE
;(plus 4 5)
;(if (= 4 0) 5 (plus (dec 4) (inc 5))))
;(plus (dec 4) (inc 5))
;(plus (- 4 1) (+ 5 1))
;(plus 3 (+ 5 1))
;(plus 3 6)
;(if (= 3 0) 6 (plus (dec 3) (inc 6))))
;(plus (dec 3) (inc 6))
;(plus (- 3 1) (+ 6 1))
;(plus 2 (+ 6 1))
;(plus 2 7)
;(if (= 2 0) 7 (plus (dec 2) (inc 7))))
;(plus (dec 2) (inc 7))
;(plus (- 2 1) (+ 7 1))
;(plus 1 (+ 7 1))
;(plus 1 8)
;(if (= 1 0) 8 (plus (dec 1) (inc 8))))
;(plus (dec 1) (inc 8))
;(plus (- 1 1) (+ 8 1))
;(plus 0 (+ 8 1))
;(plus 0 9)
;(if (= 0 0) 9 (plus (dec 0) (inc 9))))
;9

;Es iterativo porque no deja ninguna operacion pendiente