#lang racket

#|
Hecho por
EZQUERRA CEBALLOS, CARLOS
FERNÁNDEZ RIVERA, CRISTIAN MANUEL
GOMEZ GARCIA, GABRIEL
MUÑOZ FERNANDEZ, PAULA

Exercise 1.9: Each of the following two procedures defines a method for adding two positive integers 
in terms of the procedures inc, which increments its argument by 1, and dec, which decrements its argument by 1.

(define (inc x) (+ x 1))
(define (dec x) (- x 1))

(define (plus a b)
  (if (= a 0) 
      b 
      (inc (plus (dec a) b))))

(define (plus a b)
  (if (= a 0) 
      b 
      (plus (dec a) (inc b))))

Using the substitution model, illustrate the process generated by each procedure in evaluating (plus 4 5). 
Are these processes iterative or recursive?
|#

; Ponemos la pila de llamadas que se va a ir creando sin ser precisos con el metodo de sustitucion.

; Proceso para la primera versión de `plus`:
; (plus 4 5)
; (inc (plus 3 5))
; (inc (inc((plus 2 5))))
; (inc (inc (inc ((plus 1 5)))))
; (inc (inc (inc (inc ((plus 0 5))))))
; (inc (inc (inc (inc (5)))))
; (inc (inc (inc 6)))
; (inc (inc 7))
; (inc 8)
; 9

; Proceso para la segunda versión de `plus`:
; (plus 4 5)
; (plus 3 6)
; (plus 2 7)
; (plus 1 8)
; (plus 0 9)
; 9

; Como vemos, ambos son procedimientos recursivos ya que involucran llamadas a si mismos pero,
; al fijarnos en la pila de llamadas, vemos que el primero actuca como un proceso recursivo
; llevamdo la pila de llamadas hasta el final y luego acabando mientras que, en el segundo caso
; la pila de llamadas se va vaciando a medida que se van realizando las llamadas ya que
; al llamarse, acaba esa llamada y no necesita guardar nada de la anterior. Así,
; en el segundo caso, se trata de un proceso iterativo