#lang racket

; Exercise 3.11

(define (make-account balance)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount)) balance)
        "Insufficient funds"))

  (define (deposit amount)
    (set! balance (+ balance amount)) balance)

  (define (dispatch m)
    (cond 
        ((eq? m 'withdraw) withdraw)
        ((eq? m 'deposit) deposit)
        (else (error "Unknown request: MAKE-ACCOUNT" m))))

  dispatch
)

; Show the environment structure generated by the sequence of interactions

(define acc (make-account 50))
((acc 'deposit) 40)
((acc 'withdraw) 60)
(define acc2 (make-account 100))




; Evaluación de (define acc (make-account 50))
; 
; Llamamos a la función make account con el argumento 50. Después se crea 
; el entorno E1 que contiene las funciones withdraw, deposit y dispatch. A 
; su vez, se crea en E1 una variable local balance y almacena el valor 50.
; Finalmente se devuelve la función dispatch, que es asignada en acc y esta
; es a su vez guardada en global_env.
;
;  _________________________________________________________
; |                                                         |
; |    global env:                                          |
; |            - make-account:   - Código de la función     |
; |                              - Puntero: global_env      |
; |            - acc:  o                                    |
; |____________________|____________________________________|
;                      |             ↑     
;                      |             |     
;                      |             |     
;  ____________________↓_____________|________________________ 
; |                 |                                         |
; |     codigo      |     ambiente: E1                        |
; |_________________|-----------------------------------------|
;                   |     balance: 50                         |
;                   |                                         |
;                   |     withdraw:   - Código de la función  |
;                   |                 - Puntero: E1           |
;                   |                                         |
;                   |     deposit:    - Código de la función  |
;                   |                 - Puntero: E1           |
;                   |                                         |
;                   |     dispatch:   - Código de la función  |
;                   |                 - Puntero: E1           |
;                   |_________________________________________|




; Evaluación de ((acc 'deposit) 40)
; 
; Llamamos a (acc 'deposit) que ejecutará la función dispatch con el argumento
; 'deposit, devolviento así la función deposit. Esta función deposit, tomará el
; valor 40 como argumendo y actualizará en E1 el valor local de la de balance 
; (balance = balance + 40).
;
;  _________________________________________________________
; |                                                         |
; |    global env:                                          |
; |            - make-account:   - Código de la función     |
; |                              - Puntero: global_env      |
; |            - acc:  o                                    |
; |____________________|____________________________________|
;                      |             ↑     
;                      |             |     
;                      |             |     
;  ____________________↓_____________|________________________ 
; |                 |                                         |
; |     codigo      |     ambiente: E1                        |
; |_________________|-----------------------------------------|
;                   |     balance: 90                         |
;                   |                                         |
;                   |     withdraw:   - Código de la función  |
;                   |                 - Puntero: E1           |
;                   |                                         |
;                   |     deposit:    - Código de la función  |
;                   |                 - Puntero: E1           |
;                   |                                         |
;                   |     dispatch:   - Código de la función  |
;                   |                 - Puntero: E1           |
;                   |_________________________________________|




; Evaluación de ((acc 'withdraw) 60)
; 
; Llamamos a (acc 'withdraw) que ejecutará la función dispatch con el argumento
; 'withdraw, devolviendo así la función withdraw. Esta función withdraw, tomará el
; valor 60 como argumento y actualizará en E1 el valor local de la de balance 
; (balance = balance - 60).
;
;  _________________________________________________________
; |                                                         |
; |    global env:                                          |
; |            - make-account:   - Código de la función     |
; |                              - Puntero: global_env      |
; |            - acc:  o                                    |
; |____________________|____________________________________|
;                      |             ↑     
;                      |             |     
;                      |             |     
;  ____________________↓_____________|________________________ 
; |                 |                                         |
; |     codigo      |     ambiente: E1                        |
; |_________________|-----------------------------------------|
;                   |     balance: 30                         |
;                   |                                         |
;                   |     withdraw:   - Código de la función  |
;                   |                 - Puntero: E1           |
;                   |                                         |
;                   |     deposit:    - Código de la función  |
;                   |                 - Puntero: E1           |
;                   |                                         |
;                   |     dispatch:   - Código de la función  |
;                   |                 - Puntero: E1           |
;                   |_________________________________________|






; Where is the local state for `acc` kept? 
;
; El estado local de `acc` es guardado en el entorno E1, este almacena
; tanto la variable balance como las funciones.



; Suppose we define another account (define acc2 (make-account 100))
;
; Al igual que antes se llama a la función make account con el argumento 
; 100. Después se crea el entorno E2 que contiene las funciones withdraw,
; deposit y dispatch. A su vez, se crea en E2 una variable local balance
; y almacena el valor 100. Finalmente se devuelve la función dispatch, que
; es asignada en `acc2` y esta es a su vez guardada en global_env.
;
;  __________________________________________________________________________________________________________________________________
; |                                                                                                                                  |
; |    global env:                                                                                                                   |
; |            - make-account:   - Código de la función                                                                              |
; |                              - Puntero: global_env                                                                               |
; |                                                                                                                                  |
; |            - acc2: o---------------------------------------------------------------------+                                       |
; |                                                                                          |                                       |
; |            - acc:  o                                                                     |                                       |
; |____________________|_____________________________________________________________________|_______________________________________|
;                      |             ↑                                                       |             ↑                                 
;                      |             |                                                       |             |                              
;                      |             |                                                       |             |                            
;  ____________________↓_____________|________________________           ____________________↓_____________|________________________ 
; |                 |                                         |         |                 |                                         |
; |     codigo      |     ambiente: E1                        |         |     codigo      |     ambiente: E2                        |
; |_________________|-----------------------------------------|         |_________________|-----------------------------------------|
;                   |     balance: 30                         |                           |     balance: 100                         |
;                   |                                         |                           |                                         |
;                   |     withdraw:   - Código de la función  |                           |     withdraw:   - Código de la función  |
;                   |                 - Puntero: E1           |                           |                 - Puntero: E2           |
;                   |                                         |                           |                                         |
;                   |     deposit:    - Código de la función  |                           |     deposit:    - Código de la función  |
;                   |                 - Puntero: E1           |                           |                 - Puntero: E2           |
;                   |                                         |                           |                                         |
;                   |     dispatch:   - Código de la función  |                           |     dispatch:   - Código de la función  |
;                   |                 - Puntero: E1           |                           |                 - Puntero: E2           |
;                   |_________________________________________|                           |_________________________________________|



; How are the local states for the two accounts kept distinct?
;
; Las llamadas a make-account crean un nuevo entorno cada vez. Se ha creado
; para acc E1 y para acc2 E2. De este modo cada entorno guarda una instancia
; diferente de la variable balance.


; Which parts of the environment structure are shared between `acc` and `acc2`?
;
; Lo único que comparten esel global_env. Todo lo demás está contenido en sus
; respectivos entornos.
; Aunque podríamos pensar que el código de las funciones `deposit`, `withdraw`
; y `dispatch` es el mismo en ambos entornos. Sin embargo esto no es así, aunque
; podría ser una optimización a contemplar.