#lang racket
;Exercise 3.11: Will discuss as a group. In 3.2.3 we saw how the environment model described the behavior of procedures with local state.
;Now we have seen how internal definitions work. A typical message-passing procedure contains both of these aspects. Consider the bank account procedure of 3.1.1:

(define (make-account balance)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance 
                     (- balance 
                        amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch m)
    (cond ((eq? m 'withdraw) withdraw)
          ((eq? m 'deposit) deposit)
          (else (error "Unknown request: 
                        MAKE-ACCOUNT" 
                       m))))
  dispatch)
;Show the environment structure generated by the sequence of interactions

(define acc (make-account 50))

((acc 'deposit) 40)
;90

((acc 'withdraw) 60)
;30
;Where is the local state for acc kept? Suppose we define another account

(define acc2 (make-account 100))
;How are the local states for the two accounts kept distinct? Which parts of the environment structure are shared between acc and acc2?

;Cuando se ejecuta el metodo make-account se crea un nuevo ambiente que esta enlazado al ambiente global y dando un valor al argumento.
;En este caso, se introducen al ambiente 3 funciones dispatch, deposit, withdraw
;Al evaluar ((acc 'deposit) 40), se llama a la funcion dispatch con m = 'deposit y devuelve la funcion deposit, esta es llamada con amount = 40

;Ambiente al llamar a (define acc (make-account 50))
;-----------------------------------
;| Ambiente global                 |
;|                                 |
;| make-account                    |
;-----------------------------------
;  |
;  v
;------------------------------
;| codigo      |  ambiente    |
;|-------------|              |
;              | balance = 50 |
;              | dispatch:    |  --> ---------------------
;              |              |      |codigo | ambiente  |
;              |              |      ---------------------
;              |              |
;              | withdraw:    |  --> ---------------------
;              |              |      |codigo | ambiente  |
;              |              |      ---------------------
;              |              |
;              | deposit:     |  --> ---------------------
;              |              |      |codigo | ambiente  |
;              |              |      ---------------------
;              ----------------

;Ambiente al llamar a ((acc 'deposit) 40)
;-----------------------------------
;| Ambiente global                 |
;|                                 |
;| make-account                    |
;-----------------------------------
;  |
;  v
;------------------------------
;| codigo      |  ambiente    |
;|-------------|              |
;              | balance = 90 |
;              | dispatch:    |  --> --------------------------------
;              |              |      |codigo | ambiente m: 'deposit |
;              |              |      --------------------------------
;              |              |
;              | withdraw:    |  --> ---------------------
;              |              |      |codigo | ambiente  |
;              |              |      ---------------------
;              |              |
;              | deposit:     |  --> --------------------------------
;              |              |      |codigo | ambiente amount: 40  |
;              |              |      --------------------------------
;              ----------------
;Ambiente al llamar a ((acc 'withdraw) 60)
;-----------------------------------
;| Ambiente global                 |
;|                                 |
;| make-account                    |
;-----------------------------------
;  |
;  v
;------------------------------
;| codigo      |  ambiente    |
;|-------------|              |
;              | balance = 30 |
;              | dispatch:    |  --> --------------------------------
;              |              |      |codigo | ambiente m: 'withdraw|
;              |              |      --------------------------------
;              |              |
;              | withdraw:    |  --> --------------------------------
;              |              |      |codigo | ambiente  amount: 60 |
;              |              |      --------------------------------
;              |              |
;              | deposit:     |  --> -------------------
;              |              |      |codigo | ambiente|
;              |              |      -------------------
;              ----------------


;Al crear otra cuenta solo se comparte el ambiente global, cada una tiene su propio ambiente individual por ejemplo
;-----------------------------------
;| Ambiente global                 |
;|                                 |
;| make-account                    |  -----------------------> ------------------------------
;-----------------------------------                           | codigo      |  ambiente    |
;  |                                                           |-------------|              |
;  v                                                                         | balance = 50 |
;------------------------------                                              | dispatch:    |  --> ---------------------
;| codigo      |  ambiente    |                                              |              |      |codigo | ambiente  |
;|-------------|              |                                              |              |      ---------------------
;              | balance = 50 |                                              |              |
;              | dispatch:    |  --> ---------------------                   | withdraw:    |  --> ---------------------
;              |              |      |codigo | ambiente  |                   |              |      |codigo | ambiente  |
;              |              |      ---------------------                   |              |      ---------------------
;              |              |                                              |              |
;              | withdraw:    |  --> ---------------------                   | deposit:     |  --> ---------------------
;              |              |      |codigo | ambiente  |                   |              |      |codigo | ambiente  |
;              |              |      ---------------------                   |              |      ---------------------
;              |              |                                              ----------------
;              | deposit:     |  --> ---------------------
;              |              |      |codigo | ambiente  |
;              |              |      ---------------------
;              ----------------