#lang racket
(define lista1 (list 1 3 (list 5 7) 9))
(define lista2 (list (list 7)))
(define lista3 (list 1 (list 2 (list 3 (list 4 (list 5 (list 6 7)))))))

(display lista1)
(newline)
(display lista2)
(newline)
(display lista3)

(newline)
(newline)
(display "Lista 1")
(newline)
(car(cdr(car(cdr(cdr lista1)))))
(newline)
(display "Lista 2")
(newline)
(car (car lista2))
(newline)
(display "Lista 3")
(newline)
(car(cdr(car(cdr(car(cdr(car(cdr(car(cdr(car(cdr lista3))))))))))))