#lang racket
; Las cajas alice tienen como parámetro las coordenadas de abajo izq (x1 y1) y las de arriba der (x2 y2)
(define (alice-make-box x1 y1 x2 y2)
  (list 'alice-box x1 y1 x2 y2))
; Las cajas bob tienen como parametro las coordenadas abajo izq (x1 y1) y el incremento en x (x2) y el incremento en y (y2)
(define (bob-make-box x1 y1 delta_x delta_y)
  (list 'bob-box x1 y1 delta_x delta_y))

(define (area box)
  (let ((tag (list-ref box 0))
        (x1 (list-ref box 1))
        (y1 (list-ref box 2))
        (x2 (list-ref box 3))
        (y2 (list-ref box 4)))
    (cond ((equal? tag 'alice-box)
           (* (abs (- x2 x1)) (abs (- y2 y1))))
          ((equal? tag 'bob-box)
           (* x2 y2)))))

(define (width box)
  (let ((tag (list-ref box 0))
        (x1 (list-ref box 1))
        (y1 (list-ref box 2))
        (x2 (list-ref box 3))
        (y2 (list-ref box 4)))
    (cond ((equal? tag 'alice-box)
           (abs (- x2 x1)))
          ((equal? tag 'bob-box)
           x2))))

(define (height box)
  (let ((tag (list-ref box 0))
        (x1 (list-ref box 1))
        (y1 (list-ref box 2))
        (x2 (list-ref box 3))
        (y2 (list-ref box 4)))
    (cond ((equal? tag 'alice-box)
           (abs (- y2 y1)))
          ((equal? tag 'bob-box)
           y2))))

(define a (alice-make-box 1 2 3 4))

(define b (bob-make-box 1 2 3 4))